customhost = "employee.cf403jikrrll.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "bait3273"
customdb = "employee"
custombucket = "danielwongtingpoh-employee"
customregion = "us-east-1"
